// Normalisation at the boundary, and the vocabulary of reasons. Shared by both
// languages, and deliberately holding nothing that is either language's.
//
// `CLAUDE.md`: *"String comparison, normalisation (NFC vs NFD) and sorting are real
// problems here: a word typed by the mother and a word generated by the pipeline must
// compare equal. Normalise at the boundary, once, and test it."* This is that boundary.

import { nfc } from '../engine/text.mjs';

/** Every problem the editor can report. The UI keys its sentences off these. */
export const PROBLEMS = [
  'empty', // nothing typed yet
  'twoSyllables', // `máy bay` — v1 builds one syllable (K1)
  'notOnTheAlphabet', // a character outside this board's alphabet (K10, K14)
  'unknownRime', // the onset is known and the rime is not (K2)
  'unknownOnset', // the leading consonants are not a first sound this pack knows
  'noParse', // nothing at all was recognised (K7)
  'illegalSpelling', // `k` before a back vowel (`literacy-vi.md` §4.1)
  'tooLong', // more than six letters (X8)
];

/**
 * **Normalisation, at the boundary, once.** NFC so that a word she typed on a phone
 * keyboard and a word the pipeline generated compare equal, then trimmed, then folded to
 * lower case.
 *
 * *Folding is a recorded deviation and it is small.* `content-pipeline.md` §3.8 leaves
 * `word.text` free of the D20 case rule so `Hà Nội` is legitimate — but `letters`, `tiles`
 * and the English `letters.join('') === text` identity are all lower case and are all hard
 * errors in the loader, so a capital she types would make her own word unplayable in
 * English and inconsistent in Vietnamese. Folding once, here, is the only place that can
 * happen and she sees the folded form on the very next screen (§13.3a), so nothing is
 * changed behind her back. D24 forbids *upper*-casing what she typed; it is not touched.
 */
export function normaliseTyped(text) {
  return nfc(String(text ?? '')).trim().replace(/\s+/g, ' ').toLowerCase();
}

export function problem(code, detail = {}) {
  return { code, ...detail };
}
