// **She types a word; the app derives the rest.** This is that, against the real packs.
//
// `content-pipeline.md` §3.7 and `ui.md` §13.7 E19 say `letters` and `onsetLetterCount`
// are written by the editor and never composed at runtime. The strongest available check
// on the thing that writes them is that it **reproduces every decomposition in both
// shipped packs from the spelling alone** — 47 Vietnamese words and 40 English ones,
// authored months earlier by a different tool from a different source. That is the first
// test below, and it is a fixture nobody can quietly weaken, because weakening it means
// changing the content.
//
// The rest is `ui.md` §13.3 / §13.3a: every screen his mother can land on, reached by
// asking the model what it says about the word that lands her there.

import test from 'node:test';
import assert from 'node:assert/strict';

import { viPack, enPack } from './helpers/load.mjs';
import {
  analyse, normaliseTyped, bareLetters, spansOf, needsConfirm, viRimeProposal,
  MAX_WORD_LETTERS, PROBLEMS,
} from '../src/editor/model.mjs';
import { buildWordRecord } from '../src/editor/wordFile.mjs';
import { buildList } from '../src/editor/list.mjs';
import { resolvePack, createGame, createSession, tableView } from '../src/engine/index.mjs';
import { readPackInputs, packDir } from './helpers/load.mjs';

const vi = viPack();
const en = enPack();

/* ------------------------------------------- the fixture nobody can weaken */

test('every vi-seed word is re-derived from its spelling alone, boundary included', () => {
  assert.equal(vi.words.length, 47, 'the fixture is the shipped pack; if it changed, re-read this');
  for (const word of vi.words) {
    const { choice, problem } = analyse(vi, word.text);
    assert.equal(problem, null, `${word.text}: ${problem && problem.code}`);
    const stored = word.syllables[0];
    assert.deepEqual(
      { onset: choice.onset, rime: choice.rime, tone: choice.tone },
      { onset: stored.onset, rime: stored.rime, tone: stored.tone },
      `${word.text} was read as a different syllable`,
    );
    assert.deepEqual(choice.letters, word.letters, `${word.text}: letters`);
    // **The boundary is the point.** `chó` is `c h | o`, and a first-vowel rule gets
    // `gi` and `qu` wrong, which is exactly why it is stored (C4f).
    assert.equal(choice.onsetLetterCount, word.onsetLetterCount, `${word.text}: boundary`);
  }
});

test('every en-seed word is re-derived, and `duck` is three sounds and four taps', () => {
  assert.equal(en.words.length, 40);
  for (const word of en.words) {
    const { choice, problem } = analyse(en, word.text);
    assert.equal(problem, null, `${word.text}: ${problem && problem.code}`);
    assert.deepEqual(choice.tiles, word.tiles, `${word.text}: sounds`);
    assert.deepEqual(choice.letters, word.letters, `${word.text}: taps`);
  }
  const duck = analyse(en, 'duck').choice;
  assert.deepEqual(duck.tiles, ['d', 'u', 'ck']);
  assert.deepEqual(duck.letters, ['d', 'u', 'c', 'k']);
  // Fewest tiles wins, and that is what puts `gg` together rather than apart.
  assert.deepEqual(analyse(en, 'egg').choice.tiles, ['e', 'gg']);
});

test('the derived record round-trips through the loader and becomes playable', () => {
  // The end-to-end claim: what the editor writes, the engine accepts. Anything less is a
  // decomposition that looks right on her screen and withholds the word on his.
  const inputs = readPackInputs(packDir('vi-seed'));
  const record = buildWordRecord(
    {
      id: 'wtest', text: 'mèo', images: [{ src: 'media/img/x.jpg' }],
      audio: { word: { src: 'media/aud/x.mp3' } }, draft: false,
      choice: analyse(vi, 'mèo').choice,
    },
    { language: 'vi' },
  );
  const resolved = resolvePack({
    language: 'vi',
    manifest: inputs.manifest,
    // `mèo` is already in the pack, so this word would clash on parts; drop the original.
    words: [...inputs.words.filter((w) => w.id !== 'meo'), record],
    hasMedia: (ref) => inputs.hasMedia(ref) || ref.startsWith('media/img/x') || ref.startsWith('media/aud/x'),
  });
  const built = resolved.wordById.wtest;
  assert.ok(built, `the editor's own record was withheld: ${JSON.stringify(
    resolved.catalogue.find((c) => c.id === 'wtest'),
  )}`);
  assert.deepEqual(built.letters, ['m', 'e', 'o']);
  assert.equal(built.onsetLetterCount, 1);
});

/* --------------------------------------------- normalisation at the boundary */

test('normalisation happens once, at the boundary, and NFD equals NFC', () => {
  // `CLAUDE.md`: *a word typed by the mother and a word generated by the pipeline must
  // compare equal.* A phone keyboard can hand back either form.
  // Written as an escape on purpose: an editor that normalises this file would
  // otherwise turn the test into a tautology without anything failing.
  const nfd = 'me\u0300o'; // m + e + COMBINING GRAVE + o
  assert.equal([...nfd].length, 4);
  assert.notEqual(nfd, 'mèo');
  assert.equal(normaliseTyped(nfd), 'mèo');
  assert.deepEqual(analyse(vi, nfd).choice.letters, ['m', 'e', 'o']);
  assert.equal(analyse(vi, nfd).choice.tone, 'huyen');
  // Trimmed, collapsed, folded — and D24 is untouched: nothing is ever upper-cased.
  assert.equal(normaliseTyped('  MÈO  '), 'mèo');
  assert.equal(normaliseTyped('Cat'), 'cat');
  assert.equal(normaliseTyped('máy   bay'), 'máy bay');
});

test('D20 — every letter the editor writes is lower case and one character', () => {
  for (const [pack, word] of [[vi, 'MÈO'], [en, 'DUCK']]) {
    const choice = analyse(pack, word).choice;
    for (const letter of choice.letters) {
      assert.equal(letter, letter.toLowerCase(), `${letter} is stored upper case`);
      assert.equal([...letter.normalize('NFC')].length, 1);
    }
  }
});

/* ------------------------------------------------ §13.3a — too long (X7, X8) */

test('X8 — a word longer than the strip is refused, with the letters to draw', () => {
  const looked = analyse(vi, 'nghiêng');
  assert.equal(looked.problem.code, 'tooLong');
  // `ui.md` §13.3a's own example: n-g-h-i-ê-n-g, seven cells against six.
  assert.deepEqual(looked.problem.letters, ['n', 'g', 'h', 'i', 'ê', 'n', 'g']);
  assert.equal(looked.problem.limit, MAX_WORD_LETTERS);
  // It fires even though the rime `iêng` is not in the pack either, because the length is
  // the thing she can act on: adding the rime would not make it fit.
  assert.equal(bareLetters('vi', 'nghiêng').length, 7);
});

test('X8 — the English side, and the letters the screen draws are the whole word', () => {
  const looked = analyse(en, 'stretch');
  assert.equal(looked.problem.code, 'tooLong');
  // §13.3a draws the strip **to scale with the extra letter falling off the end**, so the
  // problem carries all seven: six cells and one that does not fit.
  assert.deepEqual(looked.problem.letters, ['s', 't', 'r', 'e', 't', 'c', 'h']);
  assert.equal(looked.problem.letters.length, MAX_WORD_LETTERS + 1);
});

test('X8 — the word is still SAVED, with its picture and its recording', () => {
  const record = buildWordRecord(
    {
      id: 'wlong', text: 'nghiêng', images: [{ src: 'media/img/x.jpg' }],
      audio: { word: { src: 'media/aud/x.mp3' } }, draft: false, choice: null,
      disabledReason: 'tooLong',
    },
    { language: 'vi', over: true },
  );
  assert.equal(record.text, 'nghiêng');
  assert.equal(record.images.length, 1, 'her photograph was thrown away');
  assert.equal(record.audio.word.src, 'media/aud/x.mp3', 'her recording was thrown away');
  assert.equal(record.enabled, false);
  // And it is filed under *Chưa chơi được* with the reason, not hidden (J2).
  const row = buildList({ words: [record], pack: vi }).notYet[0];
  assert.equal(row.section, 'notYet');
  assert.equal(row.reason.code, 'tooLong');
});

test('X6/X7 — a six-letter word is fine and a seven-letter one is not, at the boundary', () => {
  const six = analyse(en, 'branch');
  assert.equal(six.choice.letters.length, 6);
  assert.equal(six.problem, null);
  assert.equal(analyse(en, 'branchy').problem.code, 'tooLong');
});

/* ------------------------------------- §13.3 — the four screens she can land on */

test('K1 — two syllables is one sentence and each syllable is a one-tap correction', () => {
  const looked = analyse(vi, 'máy bay');
  assert.equal(looked.problem.code, 'twoSyllables');
  assert.deepEqual(looked.problem.syllables, ['máy', 'bay']);
  // And each of them, taken on its own, is a word the model can read.
  assert.equal(analyse(vi, 'bay').problem, null);
});

test('K2 — an unknown rime names what was recognised and what was not', () => {
  const looked = analyse(vi, 'xoài');
  assert.equal(looked.problem.code, 'unknownRime');
  assert.equal(looked.problem.onset, 'x', 'the onset it DID recognise must be named');
  assert.equal(looked.problem.rime, 'oai', 'the unknown rime must be the BARE form she can add');
  assert.equal(looked.problem.tone, 'huyen');
});

test('K3/K4/K5 — all six toned forms are generated, stored, and the illegal ones are null', () => {
  const open = viRimeProposal('uông');
  assert.deepEqual(open.legalTones, ['ngang', 'huyen', 'sac', 'hoi', 'nga', 'nang']);
  assert.deepEqual(open.toned, {
    ngang: 'uông', huyen: 'uồng', sac: 'uống', hoi: 'uổng', nga: 'uỗng', nang: 'uộng',
  });
  // §5.2's checked-syllable rule, greyed on the screen and **null in the pack**.
  const stopped = viRimeProposal('oat');
  assert.deepEqual(stopped.legalTones, ['sac', 'nang']);
  assert.deepEqual(stopped.cells.filter((c) => c.legal).map((c) => c.tone), ['sac', 'nang']);
  for (const cell of stopped.cells) {
    if (!cell.legal) assert.equal(cell.form, null);
    else assert.equal(typeof cell.form, 'string');
  }
  // Every generated form is NFC, so it compares equal to what she types.
  for (const form of Object.values(open.toned)) assert.equal(form, form.normalize('NFC'));
});

test('K3 — the generator agrees with every rime already in the pack', () => {
  // The forms it will propose for a rime she adds are made the same way the 35 shipped
  // rimes were. If it disagrees with them it is wrong, and this is how we would know.
  for (const rime of vi.tiles.rime) {
    const proposed = viRimeProposal(rime.id);
    for (const tone of rime.legalTones) {
      assert.equal(proposed.toned[tone], rime.toned[tone],
        `rime ${rime.id} + ${tone}: proposed ${proposed.toned[tone]}, pack has ${rime.toned[tone]}`);
    }
  }
});

test('K10/K14 — a character outside the alphabet is named, and only that character', () => {
  const looked = analyse(vi, 'fish');
  assert.equal(looked.problem.code, 'notOnTheAlphabet');
  assert.deepEqual(looked.problem.characters, ['f']);
  // Revision 5 makes this rare on purpose: the board is the WHOLE alphabet, so a toned
  // letter is never off it. `ố` is `o` plus a tone she presses afterwards.
  assert.equal(analyse(vi, 'quốc').problem.code, 'unknownRime');
  assert.deepEqual(analyse(en, 'ê').problem.characters, ['ê']);
});

test('K7 — nothing recognised is still a problem with a code, never a refusal', () => {
  // `bcd` is three Vietnamese letters and no syllable; `ay` is two English letters that
  // no tiling can legalise, because `y` may only start a word (`literacy-en.md` §3.3).
  for (const [pack, word] of [[vi, 'bcd'], [en, 'ay']]) {
    const looked = analyse(pack, word);
    assert.equal(looked.choice, null);
    assert.ok(PROBLEMS.includes(looked.problem.code), looked.problem.code);
  }
});

test('K6 — the word "invalid" appears in no problem code and no reason string', () => {
  for (const code of PROBLEMS) assert.ok(!/invalid/i.test(code), code);
  const enStrings = JSON.stringify(Object.keys(vi.catalogue));
  void enStrings;
  for (const word of ['máy bay', 'fish', 'nghiêng', 'bzz', '']) {
    const looked = analyse(vi, word);
    assert.ok(!/invalid/i.test(JSON.stringify(looked.problem ?? {})));
  }
});

/* ------------------------------------ §13.3a — the confirm screen, and when not */

test('S19 fires for a digraph, `gi` and `qu`, and `bò` skips it entirely', () => {
  // §13.3a: *"It appears **only** when the decomposition is not one letter per unit, i.e.
  // when a digraph or `gi` / `qu` is involved; `bò` skips it entirely."*
  assert.equal(analyse(vi, 'chó').needsConfirm, true, 'ch is two letters, one sound');
  assert.equal(analyse(vi, 'già').needsConfirm, true);
  assert.equal(analyse(vi, 'quả').needsConfirm, true);
  assert.equal(analyse(vi, 'bò').needsConfirm, false);
  // A two-letter RIME is not a reason to ask her: `mèo`'s boundary is where her own
  // spelling puts it, and asking about it would train her to dismiss the screen.
  assert.equal(analyse(vi, 'mèo').needsConfirm, false);
  assert.equal(analyse(vi, 'áo').needsConfirm, false);
  // English: any digraph.
  assert.equal(analyse(en, 'ship').needsConfirm, true);
  assert.equal(analyse(en, 'cat').needsConfirm, false);
});

test('the spans the confirm screen draws are the spans the board will draw', () => {
  for (const word of vi.words) {
    const choice = analyse(vi, word.text).choice;
    assert.deepEqual(
      spansOf(choice).map((s) => [s.start, s.end, s.kind]),
      word.spans.map((s) => [s.start, s.end, s.kind]),
      `${word.text}: the editor and the board disagree about the spans`,
    );
  }
  for (const word of en.words) {
    const choice = analyse(en, word.text).choice;
    assert.deepEqual(
      spansOf(choice).map((s) => [s.start, s.end, s.kind]),
      word.spans.map((s) => [s.start, s.end, s.kind]),
      `${word.text}: the editor and the board disagree about the spans`,
    );
  }
});

test('needsConfirm is exactly "some span covers more than one letter" in English', () => {
  for (const word of en.words) {
    const choice = analyse(en, word.text).choice;
    assert.equal(needsConfirm(choice), word.spans.some((s) => s.end - s.start > 1), word.text);
  }
});

/* --------------------------------------------------- the collapsed spelling */

test('`gì` is the onset `gi` + the rime `i` written with ONE `i`, and it says so', () => {
  // `literacy-vi.md` §1.2's own example, and the reason `build.spellingException` exists.
  const looked = analyse(vi, 'gì');
  assert.equal(looked.problem, null, 'gì must be readable, not a help screen');
  assert.equal(looked.choice.onset, 'gi');
  assert.equal(looked.choice.rime, 'i');
  assert.equal(looked.choice.tone, 'huyen');
  // Two letters, and the rime is genuinely not visible in them — which is what the stored
  // boundary is for.
  assert.deepEqual(looked.choice.letters, ['g', 'i']);
  assert.equal(looked.choice.onsetLetterCount, 2);
  assert.equal(looked.choice.spellingException, true);

  const record = buildWordRecord(
    { id: 'wgi', text: 'gì', images: [], audio: {}, draft: false, choice: looked.choice },
    { language: 'vi' },
  );
  // The waiver is written, because the loader refuses the word without it.
  assert.equal(record.build.spellingException, true);
  assert.deepEqual(record.letters, ['g', 'i']);
  assert.equal(record.onsetLetterCount, 2);
});

test('a word whose pieces do NOT overlap carries no waiver', () => {
  for (const word of ['già', 'gia', 'chó', 'mèo']) {
    const choice = analyse(vi, word).choice;
    assert.equal(choice.spellingException, false, word);
    assert.equal(
      buildWordRecord({ id: 'w', text: word, images: [], audio: {}, draft: false, choice },
        { language: 'vi' }).build.spellingException,
      undefined, word,
    );
  }
});

/* ----------------------------------------------------- more than one reading */

test('`già` has two readings and the longest onset is offered first', () => {
  const looked = analyse(vi, 'già');
  // `gi`+`a` and `g`+`ia` are both real; they put the boundary in different places, which
  // is the whole reason `onsetLetterCount` is stored rather than derived.
  assert.ok(looked.parses.length >= 1);
  assert.equal(looked.choice.onset, 'gi', 'the standard analysis is the longest onset');
  if (looked.parses.length > 1) {
    const other = analyse(vi, 'già', 1).choice;
    assert.notEqual(other.onsetLetterCount, looked.choice.onsetLetterCount);
  }
  // An index out of range is clamped rather than throwing: it comes from a tap counter.
  assert.equal(analyse(vi, 'già', 99).choice.index, looked.parses.length - 1);
  assert.equal(analyse(vi, 'già', -4).choice.index, 0);
});

/* ------------------------------------------------------------ hostile input */

test('nothing the keyboard can produce makes analyse throw', () => {
  const hostile = ['', '   ', '\n', '0', '!!!', '🙂', 'a'.repeat(400), 'mèo mèo mèo mèo',
    '\u0000', '../../etc/passwd', '<script>', 'ă'.repeat(50), 'Ｍèｏ'];
  for (const pack of [vi, en]) {
    for (const word of hostile) {
      const looked = analyse(pack, word);
      assert.ok(looked.problem === null || PROBLEMS.includes(looked.problem.code),
        `${pack.language} ${JSON.stringify(word.slice(0, 20))}: ${JSON.stringify(looked.problem)}`);
      // Nothing that parses is ever longer than the strip: the length gate runs first.
      if (looked.choice) assert.ok(looked.choice.letters.length <= MAX_WORD_LETTERS,
        `${JSON.stringify(word.slice(0, 20))} parsed to ${looked.choice.letters.length} letters`);
    }
  }
});

test('an unknown language throws rather than defaulting onto the other one (R4)', () => {
  assert.throws(() => analyse({ language: 'fr', tiles: {} }, 'chat'), /no editor model/);
  assert.throws(() => bareLetters('fr', 'chat'), /no editor model/);
});

/* ------------------------------------------------------------ the word list */

test('J2 — a word that cannot be played is in a named section with a reason, never hidden', () => {
  const words = [
    { id: 'ok', text: 'mèo', stage: 1, enabled: true, syllables: [{ onset: 'm', rime: 'eo', tone: 'huyen' }], letters: ['m', 'e', 'o'], onsetLetterCount: 1, images: [{ src: 'x' }], audio: { word: { src: 'y' } } },
    { id: 'nopic', text: 'bò', stage: 1, enabled: true, draft: true, images: [], audio: {} },
    { id: 'toolong', text: 'nghiêng', stage: 1, enabled: false, draft: true, images: [{ src: 'x' }], audio: { word: { src: 'y' } } },
  ];
  const list = buildList({ words, pack: vi, trash: [], unreadable: [] });
  const all = [...list.playable, ...list.notYet].map((r) => r.id).sort();
  assert.deepEqual(all, ['nopic', 'ok', 'toolong'], 'a word was hidden');
  for (const row of list.notYet) {
    assert.ok(row.reason && typeof row.reason.code === 'string', `${row.id} has no reason`);
  }
  assert.equal(list.notYet.find((r) => r.id === 'toolong').reason.code, 'tooLong');
  assert.equal(list.notYet.find((r) => r.id === 'nopic').reason.code, 'noPicture');
});

test('J1 — a row carries the thumbnail and the decomposition the sketch shows', () => {
  const word = vi.words.find((w) => w.text === 'mèo');
  const raw = {
    id: word.id, text: word.text, stage: word.stage, enabled: true,
    syllables: word.syllables, letters: word.letters, onsetLetterCount: word.onsetLetterCount,
    images: [{ src: word.images[0] ? word.images[0].src : 'media/img/a.jpg' }],
    audio: { word: { src: 'media/aud/a.mp3' } },
  };
  const [row] = buildList({ words: [raw], pack: vi }).playable;
  assert.equal(row.text, 'mèo');
  assert.ok(row.thumb, 'no thumbnail');
  // §13.1's own second line: `m · eo · huyền`, with the tone's **editable label**, not its id.
  assert.equal(row.decomposition, 'm · eo · huyền');
});

test('the editor never tells her a word is ready that the board withholds', () => {
  // `pack.catalogue` is the authority, and it is the object the board obeys. A row that
  // derived its own answer could say "ready" about a word that never appears.
  const inputs = readPackInputs(packDir('vi-seed'));
  const list = buildList({ words: inputs.words, pack: vi, trash: [], unreadable: [] });
  const playableInPack = new Set(vi.words.map((w) => w.id));
  for (const row of list.playable) assert.ok(playableInPack.has(row.id), `${row.id} is not in the pack`);
  for (const row of list.notYet) assert.ok(!playableInPack.has(row.id), `${row.id} IS in the pack`);
  assert.equal(list.playable.length, vi.words.length);
});

/* -------------------------------------------- L7 — deleting a word moves nothing */

test('L7 — deleting her last word behind a letter does not move a single character', () => {
  // **This is the criterion that exists *because* of the editor.** `ui.md` §8.1 draws
  // every character of `inventoryOrder` whether or not a word uses it, and L7 is what
  // stops the board from reshuffling when the word list shrinks. The slot the child has
  // learned is a pure function of `inventoryOrder` and the device, and nothing else —
  // not the word list, not the session, not a random source (E12, B7).
  const inputs = readPackInputs(packDir('vi-seed'));
  const before = createGame(vi, { pages: [15, 14, 6] });

  // `k` has exactly one word behind it in `vi-seed` (`kem`). Delete every word that uses
  // it — which is the strongest form of the case, because the letter then leads nowhere.
  const victim = 'k';
  const doomed = vi.words.filter((w) => w.letters.includes(victim)).map((w) => w.id);
  assert.ok(doomed.length > 0, `no word uses "${victim}"; pick another letter`);

  const after = createGame(
    resolvePack({
      language: 'vi',
      manifest: inputs.manifest,
      words: inputs.words.filter((w) => !doomed.includes(w.id)),
      hasMedia: inputs.hasMedia,
    }),
    { pages: [15, 14, 6] },
  );

  // 1. The alphabet is unchanged, in order.
  assert.deepEqual(after.pack.inventoryOrder, before.pack.inventoryOrder);
  // 2. **Every character is in the same cell on the same page.** Byte for byte.
  const slots = (game) => game.inventory.symbols.map((s) => `${s.id}@${s.page}:${s.slot}`);
  assert.deepEqual(slots(after), slots(before));
  assert.equal(after.pageCount, before.pageCount);
  // 3. The letter is still on the board, and it is now permanently flat.
  const cell = after.inventory.symbols.find((s) => s.id === victim);
  assert.ok(cell, `"${victim}" left the board when its last word was deleted`);
  assert.equal(tableView(after, createSession(after)).cells[cell.index].live, false);
  // 4. And it was live before, so the test is measuring something.
  assert.equal(tableView(before, createSession(before)).cells[cell.index].live, true);
});
