#!/usr/bin/env node
// Bundle the Fluent Emoji 3D fallback pictures named by the seed packs.
//
// `content-pipeline.md` §5: "The fallback cannot itself go missing. `fallbackEmoji` is a
// key into media **bundled in the app binary**, not a pack media reference. That is
// deliberate: the fallback exists precisely for the case where the pack is damaged, so
// making it editable would make it damageable."
//
// So this runs at build time, reads the names the packs actually use, and writes them
// into `assets/emoji/` with a generated index module. Adding a word with a new fallback
// name is a re-run of this script, not a runtime download — the app makes no network
// call, ever (`decisions.md`).
//
//   node scripts/build-emoji.mjs
//
// Licence: microsoft/fluentui-emoji is MIT. `tools/pack-attributions.mjs` emits the
// notice; `assets/emoji/LICENSE` carries the text.

import { mkdir, writeFile, readdir, readFile, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'assets', 'emoji');
const PACKS = path.join(ROOT, 'packs');
const REPO = 'microsoft/fluentui-emoji';

/** `Billed cap` -> `billed-cap`; the file name the app looks a fallback up by. */
export function slugOf(name) {
  return name.normalize('NFC').toLowerCase()
    .replace(/[‘’']/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

async function namesUsedByPacks() {
  const names = new Set();
  for (const packId of await readdir(PACKS)) {
    let files;
    try { files = await readdir(path.join(PACKS, packId, 'words')); } catch { continue; }
    for (const f of files) {
      if (!f.endsWith('.json')) continue;
      try {
        const w = JSON.parse(await readFile(path.join(PACKS, packId, 'words', f), 'utf8'));
        if (typeof w.fallbackEmoji === 'string' && w.fallbackEmoji) names.add(w.fallbackEmoji);
      } catch { /* a word file that will not parse is the pack validator's problem */ }
    }
  }
  return [...names].sort();
}

async function main() {
  await mkdir(OUT, { recursive: true });
  const names = await namesUsedByPacks();

  const res = await fetch(`https://api.github.com/repos/${REPO}/git/trees/main?recursive=1`);
  if (!res.ok) throw new Error(`${res.status} listing ${REPO}`);
  const tree = (await res.json()).tree;

  // Index every 3D png by the slug of its asset directory, so the lookup is the same
  // normalisation the app uses and a curly apostrophe upstream cannot break it.
  const bySlug = new Map();
  for (const node of tree) {
    const m = /^assets\/([^/]+)\/(?:Default\/)?3D\/[^/]+\.png$/.exec(node.path);
    if (m) bySlug.set(slugOf(m[1]), node.path);
  }

  const written = [];
  const missing = [];
  for (const name of names) {
    const slug = slugOf(name);
    const src = bySlug.get(slug);
    if (!src) { missing.push(name); continue; }
    const dest = path.join(OUT, `${slug}.png`);
    try { await stat(dest); written.push(slug); continue; } catch { /* not cached */ }
    const r = await fetch(`https://raw.githubusercontent.com/${REPO}/main/${encodeURI(src)}`);
    if (!r.ok) { missing.push(name); continue; }
    await writeFile(dest, Buffer.from(await r.arrayBuffer()));
    written.push(slug);
  }

  written.sort();
  const lines = [
    '// GENERATED by `node scripts/build-emoji.mjs`. Do not edit.',
    '//',
    '// The bundled fallback pictures (`content-pipeline.md` §5). A key here can never',
    '// dangle, because these are in the binary rather than in a pack his mother edits.',
    '',
    'export const EMOJI = {',
    ...written.map((s) => `  '${s}': require('./${s}.png'),`),
    '};',
    '',
  ];
  await writeFile(path.join(OUT, 'index.js'), lines.join('\n'));

  const licence = await fetch(`https://raw.githubusercontent.com/${REPO}/main/LICENSE`);
  if (licence.ok) await writeFile(path.join(OUT, 'LICENSE'), await licence.text());

  process.stdout.write(`  ${written.length} fallback pictures in assets/emoji/\n`);
  if (missing.length) {
    process.stdout.write(`  NOT FOUND upstream: ${missing.join(', ')}\n`);
    process.exitCode = 1;
  }
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  main().catch((e) => { process.stderr.write(`${e.stack}\n`); process.exit(1); });
}
